name: Run Docker Compose with Secrets
on:
  push:
    branches: [ "main" ]
jobs:
  run-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building the docker image
        run: docker-compose -build

      - name: Push images with Docker Compose
        run: docker-compose push
